config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
 devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "user_registrations" } 
  
  resources :products do
  resources :comments
end

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  
  root 'pages#landing_page'

  
  get 'pages/', to: 'pages#index' 
  get 'pages/about'
  get 'pages/contact'
  get 'pages/landing_page'
  get 'pages/index'
  post 'pages/thank_you'

  post 'payments/create', to:'payments#create'

  mount ActionCable.server => '/cable'

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
		
  validates :name, presence: true
  validates :description, presence: true
validates :colour, presence: true
validates :image_url, presence: true
  has_many :comments
  has_many :orders
  def self.search(search_term)
    if Rails.env.production?
      Product.where("name ilike ?", "%#{search_term}%")
    else
      Product.where("name LIKE ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first.rating
  end

  def lowest_rating_comment
    comments.rating_asc.first.rating
  end

  def average_rating
    comments.average(:rating).to_f
  end


  def views
    $redis.get("product:#{id}")
  end

  def viewed!
    $redis.incr("product:#{id}")
end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
 @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)     
   @product.viewed!
  end


  # GET /products/new
  def new
  
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end


  # POST /products
  # POST /products.json
  def create
  
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])

 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price_in_cents)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{params[:q]}-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p>
              <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
              
               <% if signed_in? && current_user.admin? %>
        
                <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product fromm being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div> 
  <div class="field">
  <%= form.label :colour %><br>
  <%= form.text_field :colour, id: :product_colour%>
</div>
<div class="field">
  <%= form.label :price_in_cents %><br>
  <%= form.text_field :price_in_cents, id: :price_in_cents%>
</div>
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="product-comment">

<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
 <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4 ">
    <div class="thumbnail products">
       <a class="product-image" href="/products/<%= product.id%>"><%= image_tag product.image_url, class: "img-responsive", alt: product.description%></a>
      <div class="caption">
        <% cache product do %>
        <h3  class="product"><%= product.name%></h3>
        <p class="product"><%= product.colour%></p>
        <p class="product"><%= product.description%></p>
        <h3 class="product"><%= number_to_currency((product.price_in_cents), unit: "$") %></h3>
        <p class="actions product" ><%= link_to 'Show', product %> <%= link_to 'Edit', edit_product_path(product) %> <%= link_to 'Destroy', product, method: :delete, data:{ confirm: 'Are you sure?' } %>
          <% end %>
         </p>

      </div>
    </div>

  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<br><br>
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="header">
    <h1>Our Products</h1>
  </div>
  <div class="row ">
<% cache(cache_key_for_products) do %>
  <%= render @products %>
<% end %>
   
</div>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

        

app/views/products/show.html.erb
<div class="thanks">
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p></div>

<section class="container-fluid">
  <div class="row" data-product-id ="<%= @product.id%>">
    <div class="col-md-6 col-lg-6 col-xs-12 product_div">
      <p class="product_title"><%= @product.name %> </p>
      <section class="product_image"> 
        <% if @product.image_url.present? %>
          <%= image_tag(@product.image_url, class:"img-zoom  img-responsive",  data_zoom_image: "@product.image_url") %>
        <% end %>
      </section>
      <p class="product_description"> <%= @product.description %> 
      </p>
      <p> Colour: <%= @product.colour %></p>
      <p> Price: $<%= @product.price_in_cents %> </p>
      <%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: 'shared/stripe_checkout_button' %>
      <% end %>
      <p> Average Rating: <div class="rated" id="average-rating" data-score= "<%=@product.average_rating %>"></div></p>
      <%= button_to 'Order Now', orders_path(product_id: @product.id, total: @product.price_in_cents), class: "btn btn-lg btn-fill btn-info" %>
      <%= link_to 'Edit', edit_product_path(@product), class:"show_links" %> |
      <%= link_to 'Back', :back, class:"show_links" %>

    </div>
    <div class="col-md-6 col-lg-6 col-xs-12 product_div">
      <h4 class="product_title"> <span class="glyphicon glyphicon-pencil"></span> Comments </h4>
      <div id="comments">
        <div class="alert alert-info" style="display: none" role="alert">
        A new comment was posted!</div>
        <%= render 'new_comment' %>
        <%= render 'comments' %>
      </div>
      <%= will_paginate @comments%>
      <h6 class="viewed"> Views:
        <span class="badge">
          <%= @product.views%>
        </span>
      </h6>
    </div>
  </div> 
</section>